eLearnEnglish/eLearnEnglish/src/eLearnEnglish.Web/Components/DownMusicViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Quizaldo.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Quizaldo.Web.Components
{
    public class DownMusicViewComponent : ViewComponent
    {
        private readonly IMusicService _musicRepository;

        public DownMusicViewComponent(IMusicService musicRepository)
        {
            _musicRepository = musicRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(string difficulty, int count)
        {
            if (difficulty != "")
            {
                var videos = await _musicRepository.GetDownMusicAsync(difficulty, count);
                return View(videos);
            }
            else
            {
                var videos = await _musicRepository.GetTopMusicAsync(count);
                return View(videos);
            }
        }
       
    }
}

eLearnEnglish/eLearnEnglish/src/eLearnEnglish.Web/Components/DownVideoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Quizaldo.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Quizaldo.Web.Components
{
    public class DownVideoViewComponent : ViewComponent
    {
        private readonly IVideoService _videoService;

        public DownVideoViewComponent(IVideoService videoService)
        {
            _videoService = videoService;
        }
        public async Task<IViewComponentResult> InvokeAsync(string difficulty, int count)
        {
            if (difficulty != "")
            {
                var videos = await _videoService.GetDownVideoAsync(difficulty, count);
                return View(videos);

            }
            else
            {
                var videos = await _videoService.GetTopVideoAsync(count);
                return View(videos);
            }

        }
     
    }
}

eLearnEnglish/eLearnEnglish/src/eLearnEnglish.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using eLearnEnglish.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Quizaldo.Common.ViewModels;
using Quizaldo.Models;
using Quizaldo.Services.Interfaces;
using Quizaldo.Web.Models;
using ReflectionIT.Mvc.Paging;

namespace Quizaldo.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<User> _userManager = null;
        private readonly IMapper mapper;
        private readonly IQuizService quizService;

        public HomeController(ILogger<HomeController> logger, IMapper mapper, IQuizService quizService, UserManager<User> userManager)
        {
            this.mapper = mapper;
            this.quizService = quizService;
            _logger = logger;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var quizzes = (await this.quizService.AllQuizzes())
                .Select(mapper.Map<AllQuizzesViewModel>);

            var pagedQuizzes = PagingList.Create(quizzes, 8, page);

            return this.View(pagedQuizzes);
        }
        public IActionResult Main()
        {
            ViewBag.userId = _userManager.GetUserId(HttpContext.User);
            return View();
        }
        public IActionResult ManageSiteData()
        {
            return View();
        }
        public IActionResult AllCources()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

eLearnEnglish/eLearnEnglish/src/eLearnEnglish.Web/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Quizaldo.Common.ViewModels;
using Quizaldo.Models;
using Quizaldo.Services.Interfaces;
using Quizaldo.Common.ServiceModels;

namespace Quizaldo.Web.Controllers
{
    [Authorize]
    public class QuizController : Controller
    {
        private readonly IQuizService quizService;
        private readonly IMapper mapper;

        public QuizController(IQuizService quizService, IMapper mapper)
        {
            this.quizService = quizService;
            this.mapper = mapper;
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult CreateQuiz()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> CreateQuiz(CreateQuizBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var quiz = mapper.Map<Quiz>(model);

            await this.quizService.CreateQuiz(quiz);

            return RedirectToAction("Index", "Home"); 
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteQuiz(int id)
        {
            await this.quizService.DeleteQuiz(id);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> StartQuiz(int id)
        {
            var getQuiz = await this.quizService.GetQuizById(id);

            var quiz = mapper.Map<QuizViewModel>(getQuiz);

            if (quiz == null)
            {
                return NotFound();
            }

            return this.View(quiz);
        }

        [HttpPost]
        public async Task<IActionResult> StartQuiz(QuizViewModel model)
        {
            var quiz = mapper.Map<QuizServiceModel>(model);

            await this.quizService.StartQuiz(quiz, this.User.Identity.Name);

            return RedirectToAction("Result", "UserResult", new { id=quiz.Result.Id });
        }

        public async Task<IActionResult> SearchResults(string searchTerm)
        {
            if (searchTerm == null)
            {
                return NotFound();
            }

            var foundQuizzes = await this.quizService.GetSearchingResults(searchTerm);

            var result = new SearchResultsViewModel();
            result.SearchTerm = searchTerm;
            result.Quizzes = foundQuizzes;

            return this.View(result);
        }

    }
}

eLearnEnglish/eLearnEnglish/src/eLearnEnglish.Web/Views/Home/AllCources.cshtml
@{
    ViewData["Title"] = "All cources";
}




<div class="row row-cols-1 row-cols-md-2">
    <div class="col mb-4">
        <div class="card">
            <img src="/images/course/Pre.jpg" class="card-img-top" alt="pre">
            <div class="card-body">
                <h5 class="card-title">Pre-Intermediate</h5>
                <p class="card-text">
                    Understand the general meaning of the interlocutor's statements, you can maintain a
                    simple dialogue and ask questions, but speak in short fragmentary sentences;
                    you know basic grammar quite well, but it is difficult for you to use it in spontaneous speech?
                    Then this course is for you
                </p>
            </div>
        </div>
    </div>
    <div class="col mb-4">
        <div class="card">
            <img src="/images/course/inter.jpg" class="card-img-top" alt="inter">
            <div class="card-body">
                <h5 class="card-title">Intermediate</h5>
                <p class="card-text">
                    Intermediate is the so-called "intermediate" level of
                    language proficiency, which allows you to speak
                    English fluently enough, to discuss many professional and everyday topics,
                    to understand by ear almost everything said at a normal pace
                </p>
            </div>
        </div>
    </div>
    <div class="col mb-4">
        <div class="card">
            <img src="/images/course/upper.jpg" class="card-img-top" alt="upper">
            <div class="card-body">
                <h5 class="card-title">Upper-Intermediate</h5>
                <p class="card-text">
                    The Upper-Intermediate level is a serious level of knowledge,
                    sufficient to communicate in English in almost all areas. People studying English
                    at the Upper-Intermediate level can start preparing for the international TOEFL or IELTS exams.
                </p>
            </div>
        </div>
    </div>
    <div class="col mb-4">
        <div class="card">
            <img src="/images/course/advance.jpg" class="card-img-top" alt="advance">
            <div class="card-body">
                <h5 class="card-title">Advanced</h5>
                <p class="card-text">
                    The Advanced English Course Level is focused on developing your fluency and accuracy abilities,
                    and to helping you reach a level of competence that will allow you to interact with a variety of more challenging,
                    sophisticated current topics.
                </p>
            </div>
        </div>
    </div>
</div>

eLearnEnglish/eLearnEnglish/src/eLearnEnglish.Web/Views/Home/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<AllQuizzesViewModel>
@using ReflectionIT.Mvc.Paging
@addTagHelper *, ReflectionIT.Mvc.Paging
@{ ViewData["Title"] = "Home Page"; }
<form asp-controller="Quiz" asp-action="SearchResults">
    <div class="input-group col-sm-7 mx-auto">
        <input type="text" class="form-control" name="searchTerm" style="background-color: transparent; border-radius: 1em; color:black;" placeholder="Search quizzes.." aria-label="Recipient's username" aria-describedby="basic-addon2">
        <button class="btn btn-transparent" type="submit"><i class="icon fas fa-search" style="color: white"></i></button>
    </div>
</form>
<div class="row mx-auto">
    @if (Model.Count() == 0)
    {
<div class="mx-auto card-holder">
    <div class="quizCard text-center" style="width: 20em;">
        <p>No quizzes yet.</p>
        <a class="nav-link text-dark" asp-area="" asp-controller="Quiz" asp-action="CreateQuiz" title="Create Quiz"><i class="icon fas fa-plus-square fa-2x" style="color: black"></i></a>
    </div>
</div> }
            else
            {
@foreach (var quiz in Model)
{
<div class="col-md-3 mx-auto card-holder">
    <div class="flip-card">
        <div class="flip-card-inner">
            <div class="flip-card-front">
                <img class="equalImg" src="@quiz.QuizLogoUrl" />
                <h5>Quiz </h5>
                <h4>@quiz.Name </h4>
                @if (@quiz.QuizQuestions.Count == 0)
                {
                    <p>No questions yet</p> 
                }
                    else if (@quiz.QuizQuestions.Count == 1)
                    {
                        <p>@quiz.QuizQuestions.Count question</p> 
                    }
                    else
                    {
                        <p>@quiz.QuizQuestions.Count questions</p>
                        }
            </div>
            <div class="flip-card-back">
                <div style="margin-top: 85px;">
                    <a style="padding: 10px;" asp-action="StartQuiz" asp-controller="Quiz" asp-route-id="@quiz.Id" title="Start"><i class="icon fas fa-play fa-2x" style="color: black"></i></a>
                    @if (User.IsInRole("Admin"))
                    {
<a style="padding: 10px;" asp-action="DeleteQuiz" asp-controller="Quiz" asp-route-id="@quiz.Id" title="Delete"><i class="icon fas fa-trash fa-2x" style="color: black"></i></a>}
                </div>
            </div>
        </div>
    </div>
</div>}}
</div>
<div>
    <nav>
        @Html.Partial("PagerOptions", this.Model)
    </nav>
</div>

eLearnEnglish/eLearnEnglish/src/eLearnEnglish.Web/Views/Home/Main.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<section class="jumbotron text-center">
    <div class="container">
        <h1>Welcome to eLearnEnglish</h1>

        <p class="lead text-muted">

            Grammar, tasks, vocabulary, books,
            videos - all this awaits you in eLearnEnglish.
            Join our community of people who like English!

        </p>

    </div>
</section>


<div class="py-5 bg-light">
    <div class="container">
        <h1>Music</h1>
        @await Component.InvokeAsync("DownMusic", new { difficulty = "", count = 3 })



    </div>
</div>

<div class="py-5 bg-light">

    <div class="container">
        <h1>Video</h1>
        @await Component.InvokeAsync("DownVideo", new { difficulty = "", count = 3 })
        @*<vc:top-books count="3"></vc:top-books>*@

    </div>
</div>

eLearnEnglish/eLearnEnglish/src/eLearnEnglish.Web/Views/Home/ManageSiteData.cshtml
@{
    ViewData["Title"] = "All cources";
}




<div class="row row-cols-1 row-cols-md-2">
    <div class="col mb-4">
        <div class="card">
            <img src="/images/manage/music.jpg" class="card-img-top" alt="upper">
            <div class="card-body">
                <h5 class="card-title" align="center">Add new music</h5>
                <a class="btn btn-primary" asp-controller="Music" asp-action="AddNewMusic">Add</a>
                <a class="btn btn-primary" asp-controller="Music" asp-action="EditMusic">Edit</a>
                <a class="btn btn-danger" asp-controller="Music" asp-action="AddNewMusic">Delete</a>
               
            </div>
        </div>
    </div>
    <div class="col mb-4">
        <div class="card">
            <img src="/images/manage/video.jpg" class="card-img-top" alt="upper">
            <div class="card-body">
                <h5 class="card-title" align="center">Add new video</h5>
                <a class="btn btn-primary" asp-controller="Video" asp-action="AddNewVideo">Add</a>
                <a class="btn btn-primary" asp-controller="Video" asp-action="EditVideo">Edit</a>
                <a class="btn btn-danger" asp-controller="Video" asp-action="AddNewVideo">Delete</a>
            </div>
        </div>
    </div>
    <div class="col mb-4">
        <div class="card">
            <img src="/images/manage/word.jpg" class="card-img-top" alt="upper">
            <div class="card-body">
                <h5 class="card-title" align="center">Add new word</h5>
                <a class="btn btn-primary" asp-controller="Word" asp-action="AddNewWord">Add</a>
                <a class="btn btn-primary" asp-controller="Word" asp-action="EditWord">Edit</a>
                <a class="btn btn-danger" asp-controller="Word" asp-action="AddNewWord">Delete</a>
            </div>
        </div>
    </div>
    <div class="col mb-4">
        <div class="card">
            <img src="/images/manage/sentence.jpg" class="card-img-top" alt="upper">
            <div class="card-body">
                <h5 class="card-title" align="center">Add new sentence</h5>
                <a class="btn btn-primary" asp-controller="Sentence" asp-action="AddNewSentence">Add</a>
                <a class="btn btn-primary" asp-controller="Sentence" asp-action="EditSentence">Edit</a>
                <a class="btn btn-danger" asp-controller="Sentence" asp-action="AddNewSentence">Delete</a>
            </div>
        </div>
    </div>
</div>